# Generated by Django 6.0 on 2026-01-18 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PCOR', 'PCOR Course (Parent/Coach/Official/Relations Course)'), ('CPR', 'CPR Certification'), ('ADDITIONAL_MANDATORY', 'Additional Mandatory Classes'), ('SPORTS_SAFETY', 'Basic Sports Safety and Injury Awareness'), ('MENTAL_HEALTH', 'Mental Health Awareness and Referral Basics'), ('COMPLIANCE', 'Program-Specific Compliance Training')], max_length=50)),
                ('file', models.FileField(upload_to='member_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this document')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verification status')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.participant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
