# Generated by Django 6.0 on 2026-01-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_memberdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Name of the service or sales offering', max_length=200)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('price_list', models.FileField(help_text='Upload your price list document', upload_to='vendor_price_lists/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, help_text='Optional description of your service')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False, help_text='Admin review status')),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval status')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
