# Generated by Django 6.0 on 2026-01-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vendorsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsubmission',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of discount for P.E.P. members (e.g., 10.00 for 10%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vendorsubmission',
            name='free_service_frequency',
            field=models.CharField(blank=True, help_text='How often the service is free (e.g., "Once per month", "One-time", "Annually")', max_length=200),
        ),
        migrations.AddField(
            model_name='vendorsubmission',
            name='free_service_name',
            field=models.CharField(blank=True, help_text='Name of the free service (if applicable)', max_length=200),
        ),
        migrations.AddField(
            model_name='vendorsubmission',
            name='frequency',
            field=models.CharField(blank=True, choices=[('ONE_TIME', 'One-time payment'), ('MONTHLY', 'Once a month'), ('WEEKLY', 'Once a week'), ('QUARTERLY', 'Once a quarter'), ('YEARLY', 'Once a year'), ('AS_NEEDED', 'As needed')], help_text='Frequency of service offered', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorsubmission',
            name='overall_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall value of the service', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorsubmission',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Service price', max_digits=10, null=True),
        ),
    ]
